name: flutter_dynamic_launcher_icon
description: A Flutter plugin to dynamically change the app launcher icon on Android and iOS.
version: 0.0.1
homepage: https://github.com/samiullah-dev/flutter_dynamic_launcher_icon
repository: https://github.com/samiullah-dev/flutter_dynamic_launcher_icon
issue_tracker: https://github.com/samiullah-dev/flutter_dynamic_launcher_icon/issues

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.samiullah.flutter_dynamic_launcher_icon
        pluginClass: FlutterDynamicLauncherIconPlugin
      ios:
        pluginClass: FlutterDynamicLauncherIconPlugin

screenshots:
  - description: "iOS dynamic icon change demo"
    path: screenshots/demo.gif
